name=digitalWriteFast_zephyr
version=0.0.42
author=kurte
maintainer=kurte
sentence=A library to extend digital pins on STM32 zephyr boards
paragraph=This library is a toolbox of things like digitalWriteFast and pin names support.
category=Signal Input/Output
architectures=architectures=zephyr,zephyr_main,zephyr_contrib
includes=Arduino_zephyr_toolbox.h
dot_a_linkage=true